### PR TITLE
Update install_syslinux

### PR DESCRIPTION
**Pull request by GitHubCaps**

### CODE REVIEW

**Comment by mytbk** [comment]
What distribution are you using? The original one is for Arch Linux, and there's one path at /usr/share for Gentoo.

**Comment by GitHubCaps** [comment]
Linux Mint 18.3 Sylvia x86_64 XFCE

**Comment by mytbk** [comment]
Hmm, so I need to do some work on Debian based distros.

**Comment by GitHubCaps** [comment]
I am using Ubuntu Xenial not Debian.

I am doing some testing at the moment as far as downloading (mainly updating sources) and just noticed some things on my end weren't working as they should.

**Comment by mytbk** [comment]
I've updated this script to search all possible paths, it should work now.

**Pull request closed without merging**
